services:
  nmap-monitor:
    build: .
    volumes:
      - type: bind
        source: ${WATCH_DIR}
        target: /watch
        read_only: false
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    environment:
      - WATCH_DIR=/watch
      - DEBUG=true
    ports:
      - "3000:3000"
