services:
  nmap-monitor:
    build: .
    volumes:
      - type: bind
        source: ${WATCH_DIR}
        target: /watch
        read_only: false
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    environment:
      - WATCH_DIR=/watch
      - DEBUG=true
    ports:
      - "3000:3000"

  nmap:
    image: instrumentisto/nmap
    volumes:
      - type: bind
        source: ${WATCH_DIR}
        target: /watch
        read_only: false
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"
    security_opt:
      - seccomp:unconfined
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
